export type AuthErrorCode =
  | "AUTH_EMAIL_SEND_FAILED"
  | "AUTH_INVALID_EMAIL_FROM"
  | "AUTH_RESEND_NOT_CONFIGURED"
  | "AUTH_RESEND_REJECTED"
  | "AUTH_STORAGE_NOT_CONFIGURED"
  | "AUTH_EMAIL_REQUIRED"
  | "AUTH_INVALID_REQUEST";
