export type SyncErrorCode =
  | "EMPTY_REMOTE_PAYLOAD"
  | "INVALID_REMOTE_JSON"
  | "INVALID_ENCRYPTED_ENVELOPE"
  | "DECRYPT_FAILED"
  | "UNSUPPORTED_ENCRYPTION_VERSION"
  | "SYNC_AUTH_REQUIRED"
  | "SYNC_PUSH_FAILED"
  | "SYNC_PULL_FAILED"
  | "SYNC_MANIFEST_FAILED"
  | "NON_JSON_RESPONSE"
  | "REMOTE_BACKUP_CORRUPT"
  | "NO_REMOTE_BACKUP";

export type SyncApiRoute = "manifest" | "pull" | "push" | "changes";
