.section __DATA,__ggml_metallib
.globl _ggml_metallib_start
_ggml_metallib_start:
.incbin "/Users/chiragpatel/Projects/voice-memory/apps/voicememory_mobile/native/ios/.cmake/iphoneos-arm64/llama.cpp/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal"
.globl _ggml_metallib_end
_ggml_metallib_end:
