import { countActiveInternalDashboards as countActiveFromArchiveRegistry } from "@/lib/internal/internal-archive-registry";

/**
 * Internal Complexity Reduction v1 — founder tooling separated from customer product.
 * v3: active counts delegated to internal-archive-registry.
 */
export type InternalSurfaceKind =
  | "dashboard"
  | "validator"
  | "founder_panel"
  | "experiment_panel";

export type StaleDisposition = "KEEP" | "MERGE" | "DELETE";

export interface InternalSurfaceRecord {
  id: string;
  kind: InternalSurfaceKind;
  label: string;
  route?: string;
  panelComponent?: string;
  hasEvents: boolean;
  hasUsageSignals: boolean;
  drivesDecisions: boolean;
  disposition: StaleDisposition;
  staleReason?: string;
}

/** npm validate scripts — tracked as validator surfaces (not customer UI). */
export const INTERNAL_VALIDATOR_REGISTRY: InternalSurfaceRecord[] = [
  {
    id: "validator-product-suite",
    kind: "validator",
    label: "Product & archive validators",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "validator-internal-routes",
    kind: "validator",
    label: "validate:internal-routes",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "validator-internal-complexity",
    kind: "validator",
    label: "validate:internal-complexity",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
];

/**
 * Internal panels — disposition tuned so active (KEEP) count stays under 25.
 */
export const INTERNAL_PANEL_REGISTRY: InternalSurfaceRecord[] = [
  {
    id: "founder-test-hub",
    kind: "founder_panel",
    label: "Founder test",
    route: "/internal/founder-test",
    panelComponent: "FounderTestPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "founder-review-dashboard",
    kind: "dashboard",
    label: "Founder review",
    route: "/internal/founder-review",
    panelComponent: "FounderReviewPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "product-simplification",
    kind: "founder_panel",
    label: "Product simplification",
    route: "/internal/product-simplification",
    panelComponent: "ProductSimplificationPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "archive-belief-center",
    kind: "founder_panel",
    label: "Archive belief centrality audit",
    route: "/internal/founder-test",
    panelComponent: "ArchiveBeliefCenterPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "archive-understanding",
    kind: "founder_panel",
    label: "Archive understanding",
    route: "/internal/founder-test",
    panelComponent: "ArchiveUnderstandingPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "founder-evolving-validation",
    kind: "founder_panel",
    label: "Founder evolving validation",
    route: "/internal/founder-test",
    panelComponent: "FounderEvolvingValidationPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "retention-discovery-hub",
    kind: "dashboard",
    label: "Retention discovery hub",
    route: "/internal/retention-discovery",
    panelComponent: "RetentionDiscoveryPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "retention-core-dashboard",
    kind: "dashboard",
    label: "Retention core",
    route: "/internal/retention-core",
    panelComponent: "RetentionCoreDashboard",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "blind-spot-discovery",
    kind: "experiment_panel",
    label: "Blind spot discovery",
    route: "/internal/blind-spot-discovery",
    panelComponent: "BlindSpotDiscoveryPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "emotional-integrity",
    kind: "dashboard",
    label: "Emotional integrity",
    route: "/internal/emotional-integrity",
    panelComponent: "EmotionalIntegrityPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "onboarding-clarity",
    kind: "dashboard",
    label: "Onboarding clarity",
    route: "/internal/onboarding-clarity",
    panelComponent: "OnboardingClarityDebugPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "performance-health",
    kind: "dashboard",
    label: "Performance health",
    route: "/internal/performance-health",
    panelComponent: "PerformanceHealthPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "archive-reputation-internal",
    kind: "dashboard",
    label: "Archive reputation",
    route: "/internal/archive-reputation",
    panelComponent: "ArchiveReputationPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "theory-discovery",
    kind: "experiment_panel",
    label: "Theory discovery",
    route: "/internal/theory-discovery",
    panelComponent: "TheoryDiscoveryPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "activation-metrics",
    kind: "dashboard",
    label: "Activation metrics",
    route: "/internal/retention-discovery",
    panelComponent: "ActivationMetricsPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "archive-as-product-validation",
    kind: "founder_panel",
    label: "Archive-as-product validation",
    route: "/internal/archive-belief",
    panelComponent: "ArchiveAsProductValidationPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "a-tier-dashboard",
    kind: "dashboard",
    label: "A-tier quality dashboard",
    route: "/internal/blind-spot-discovery",
    panelComponent: "ATierQualityDashboardPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "archive-voice",
    kind: "dashboard",
    label: "Archive voice consistency",
    route: "/internal/archive-voice",
    panelComponent: "ArchiveVoiceConsistencyPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "auth-value-validation",
    kind: "founder_panel",
    label: "Auth value validation",
    route: "/internal/auth-value-validation",
    panelComponent: "AuthValueValidationPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "insight-scorecard",
    kind: "experiment_panel",
    label: "Insight scorecard",
    route: "/internal/blind-spot-discovery",
    panelComponent: "InsightScorecardInternalPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "archive-belief-adoption",
    kind: "founder_panel",
    label: "Archive belief adoption",
    route: "/internal/archive-belief",
    panelComponent: "ArchiveBeliefAdoptionPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "theory-curiosity-engine",
    kind: "experiment_panel",
    label: "Theory curiosity engine",
    route: "/internal/theory-curiosity",
    panelComponent: "TheoryCuriosityEnginePanel",
    hasEvents: true,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into theory-discovery hub",
  },
  {
    id: "evolving-understanding",
    kind: "experiment_panel",
    label: "Evolving understanding",
    route: "/internal/theory-discovery",
    panelComponent: "EvolvingUnderstandingPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Duplicate on retention-discovery and theory-discovery",
  },
  {
    id: "distribution",
    kind: "dashboard",
    label: "Distribution engine",
    route: "/internal/distribution",
    panelComponent: "DistributionReportPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "KEEP",
  },
  {
    id: "organic-referral",
    kind: "dashboard",
    label: "Organic referral",
    route: "/internal/organic-referral",
    panelComponent: "OrganicReferralPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "paywall-attribution",
    kind: "dashboard",
    label: "Paywall attribution",
    route: "/internal/paywall-attribution",
    panelComponent: "PaywallAttributionPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "return-trigger",
    kind: "dashboard",
    label: "Return trigger attribution",
    route: "/internal/return-trigger-attribution",
    panelComponent: "ReturnTriggerPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "archive-attachment",
    kind: "dashboard",
    label: "Archive attachment",
    route: "/internal/archive-attachment",
    panelComponent: "ArchiveAttachmentPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "belief-recall",
    kind: "experiment_panel",
    label: "Belief recall",
    route: "/internal/retention-discovery",
    panelComponent: "BeliefRecallPanel",
    hasEvents: true,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "retention-moat",
    kind: "dashboard",
    label: "Retention moat",
    route: "/internal/retention-discovery",
    panelComponent: "RetentionMoatPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "archive-value-progress-internal",
    kind: "dashboard",
    label: "Archive value progress",
    route: "/internal/retention-discovery",
    panelComponent: "ArchiveValueProgressPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Superseded by archive progress unification",
  },
  {
    id: "value-moment-paywall",
    kind: "dashboard",
    label: "Value moment paywall",
    route: "/internal/retention-discovery",
    panelComponent: "ValueMomentPaywallPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "activation-bottleneck",
    kind: "dashboard",
    label: "Activation bottleneck",
    route: "/internal/retention-discovery",
    panelComponent: "ActivationBottleneckPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Merged into retention-discovery hub",
  },
  {
    id: "blind-spot-quality",
    kind: "experiment_panel",
    label: "Blind spot quality",
    route: "/internal/blind-spot-discovery",
    panelComponent: "BlindSpotQualityPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "insight-ingredient-optimizer",
    kind: "experiment_panel",
    label: "Insight ingredient optimizer",
    route: "/internal/blind-spot-discovery",
    panelComponent: "InsightIngredientOptimizerPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "blind-spot-experiment-loop",
    kind: "experiment_panel",
    label: "Blind spot experiment loop",
    route: "/internal/blind-spot-discovery",
    panelComponent: "BlindSpotExperimentLoopPanel",
    hasEvents: true,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "breakthrough-tracking",
    kind: "experiment_panel",
    label: "Breakthrough tracking",
    route: "/internal/blind-spot-discovery",
    panelComponent: "BreakthroughTrackingPanel",
    hasEvents: true,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "insight-outcome",
    kind: "experiment_panel",
    label: "Insight outcome",
    route: "/internal/blind-spot-discovery",
    panelComponent: "InsightOutcomePanel",
    hasEvents: true,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "self-recognition-ingredients",
    kind: "experiment_panel",
    label: "Self-recognition ingredients",
    route: "/internal/blind-spot-discovery",
    panelComponent: "SelfRecognitionIngredientsPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "blind-spot-performance",
    kind: "experiment_panel",
    label: "Blind spot performance",
    route: "/internal/blind-spot-performance",
    panelComponent: "BlindSpotPerformancePanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into blind-spot-discovery",
  },
  {
    id: "surface-primary",
    kind: "dashboard",
    label: "Surface primary",
    route: "/internal/theory-discovery",
    panelComponent: "SurfacePrimaryPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Fold into product-simplification report",
  },
  {
    id: "archive-simplicity-debug",
    kind: "dashboard",
    label: "Archive simplicity",
    route: "/internal/archive-simplicity",
    panelComponent: "ArchiveSimplicityPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events; superseded by product-simplification",
  },
  {
    id: "archive-divergence",
    kind: "dashboard",
    label: "Archive divergence",
    route: "/internal/archive-divergence",
    panelComponent: "ArchiveDivergencePanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No usage signals",
  },
  {
    id: "archive-individuality",
    kind: "dashboard",
    label: "Archive individuality",
    route: "/internal/archive-individuality",
    panelComponent: "ArchiveIndividualityPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No usage signals",
  },
  {
    id: "sacredness-review",
    kind: "dashboard",
    label: "Sacredness review",
    route: "/internal/sacredness-review",
    panelComponent: "SacrednessReviewPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events; duplicate of emotional-integrity",
  },
  {
    id: "durability-review",
    kind: "dashboard",
    label: "Durability review",
    route: "/internal/durability-review",
    panelComponent: "DurabilityReviewPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No usage signals",
  },
  {
    id: "callback-learning",
    kind: "experiment_panel",
    label: "Callback learning",
    route: "/internal/callback-learning",
    panelComponent: "CallbackLearningDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "behavior-truth",
    kind: "dashboard",
    label: "Behavior truth",
    route: "/internal/behavior-truth",
    panelComponent: "BehaviorTruthPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No usage signals",
  },
  {
    id: "reflection-friction",
    kind: "dashboard",
    label: "Reflection friction",
    route: "/internal/reflection-friction",
    panelComponent: "ReflectionFrictionPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No usage signals",
  },
  {
    id: "resurfacing-variety",
    kind: "experiment_panel",
    label: "Resurfacing variety",
    route: "/internal/resurfacing-variety",
    panelComponent: "ResurfacingVarietyPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "resurfacing-timing",
    kind: "experiment_panel",
    label: "Resurfacing timing",
    route: "/internal/resurfacing-timing",
    panelComponent: "ResurfacingTimingDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "resurfacing-confidence",
    kind: "experiment_panel",
    label: "Resurfacing confidence",
    route: "/internal/resurfacing-confidence",
    panelComponent: "ResurfacingConfidenceDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "silence-intelligence",
    kind: "experiment_panel",
    label: "Silence intelligence",
    route: "/internal/silence-intelligence",
    panelComponent: "SilenceIntelligenceDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "first-magic-moment",
    kind: "experiment_panel",
    label: "First magic moment",
    route: "/internal/first-magic-moment",
    panelComponent: "FirstMagicMomentDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "first-week-retention",
    kind: "dashboard",
    label: "First week retention",
    route: "/internal/first-week-retention",
    panelComponent: "FirstWeekRetentionDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "Superseded by retention-core",
  },
  {
    id: "recurrence-density",
    kind: "experiment_panel",
    label: "Recurrence density",
    route: "/internal/recurrence-density",
    panelComponent: "RecurrenceDensityDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "transcript-cleanup",
    kind: "dashboard",
    label: "Transcript cleanup",
    route: "/internal/transcript-cleanup",
    panelComponent: "TranscriptCleanupDebugPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "vulnerability-timing",
    kind: "experiment_panel",
    label: "Vulnerability timing",
    route: "/internal/vulnerability-timing",
    panelComponent: "VulnerabilityTimingPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "No events",
  },
  {
    id: "remembered-later",
    kind: "dashboard",
    label: "Remembered later",
    route: "/internal/founder-review",
    panelComponent: "RememberedLaterPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "Fold into founder-review",
  },
  {
    id: "share-observation",
    kind: "dashboard",
    label: "Share observation",
    route: "/internal/founder-review",
    panelComponent: "ShareObservationPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "Fold into founder-review",
  },
  {
    id: "founder-test-report",
    kind: "founder_panel",
    label: "Founder test report",
    route: "/internal/founder-test",
    panelComponent: "FounderTestReportPanel",
    hasEvents: false,
    hasUsageSignals: true,
    drivesDecisions: false,
    disposition: "MERGE",
    staleReason: "Embedded in FounderTestPanel",
  },
  {
    id: "archive-as-product-validation-embedded",
    kind: "founder_panel",
    label: "Archive-as-product (embedded)",
    route: "/internal/founder-test",
    panelComponent: "ArchiveAsProductValidationPanel",
    hasEvents: true,
    hasUsageSignals: true,
    drivesDecisions: true,
    disposition: "MERGE",
    staleReason: "Duplicate route; use archive-belief entry",
  },
  {
    id: "notification-effectiveness",
    kind: "experiment_panel",
    label: "Notification effectiveness",
    panelComponent: "NotificationEffectivenessPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "Unused panel file — no internal route",
  },
  {
    id: "theory-volatility",
    kind: "experiment_panel",
    label: "Theory volatility",
    panelComponent: "TheoryVolatilityPanel",
    hasEvents: false,
    hasUsageSignals: false,
    drivesDecisions: false,
    disposition: "DELETE",
    staleReason: "Unused panel file — no internal route",
  },
];

export function getInternalSurfaceRegistry(): InternalSurfaceRecord[] {
  return [...INTERNAL_VALIDATOR_REGISTRY, ...INTERNAL_PANEL_REGISTRY];
}

export function countActiveInternalPanels(): number {
  return countActiveFromArchiveRegistry();
}

/** v3 consolidation — max active discoverable dashboards. */
export const INTERNAL_COMPLEXITY_ACTIVE_TARGET = 12;
