import {
  DEVICE_SIGNOFF_PATH,
  EMAIL_STATUS_PATH,
  SPP20_DIR,
  STAGING_STATUS_PATH,
  STRIPE_WEBHOOK_STATUS_PATH,
} from "@/lib/proof/signoff-files";

export function printStagingProofGuide(): void {
  const lines = [
    "",
    "=== ArchiveMe staging:proof-guide ===",
    "",
    "Run on the STAGING DEPLOY HOST with secrets in the host env (never in git).",
    `Sign-off directory: ${SPP20_DIR}`,
    "",
    "0. Preflight (this machine or host)",
    "   npm run staging:setup-check",
    "   npm run staging:signoff-status",
    "",
    "1. Deploy app",
    "   - Set env from production_env_required_template.env",
    "   - VOICEMEMORY_STAGING_PROOF=1",
    "   - VOICEMEMORY_DEVICE_PROOF_REQUIRED=1",
    "   - Deploy; confirm https://<staging-host> loads",
    "",
    "2. Database proof",
    "   npm run validate:database-live",
    "   Expect exit 0. Fix migrations/SSL if exit 1.",
    "",
    "3. Stripe price lookup",
    "   (included in validate:stripe-webhook-proof)",
    "   npm run validate:stripe-webhook-proof  # may exit 2 until sign-off complete",
    "",
    "4. Stripe checkout (manual, test mode)",
    "   - Complete a test subscription checkout on staging",
    "   - Optional: VOICEMEMORY_STRIPE_PROOF_CHECKOUT=1 on host for automated test session",
    "",
    "5. Stripe webhook events (manual)",
    "   - Stripe Dashboard → Webhooks → send test events:",
    "     checkout.session.completed, customer.subscription.*, invoice.payment_failed",
    "   - Replay duplicate event id → idempotency must reject",
    "",
    "6. Update Stripe sign-off (do NOT auto-set in repo)",
    `   Edit: ${STRIPE_WEBHOOK_STATUS_PATH}`,
    "   - Set verifiedAt (ISO), verifiedBy, appUrl",
    "   - Set event booleans true only after real deliveries",
    "   - Then set STRIPE_WEBHOOK_LIVE_PROOF=1 on host",
    "",
    "7. Email",
    "   Option A: EMAIL_DISABLED=true → npm run validate:email-live (exit 0)",
    "   Option B: Resend inbox proof → edit:",
    `   ${EMAIL_STATUS_PATH}`,
    "   - deliveryVerified: true, fresh verifiedAt",
    "",
    "8. Staging live proof",
    "   VOICEMEMORY_STAGING_PROOF=1 npm run validate:staging-proof",
    `   Update: ${STAGING_STATUS_PATH}`,
    "",
    "9. Device checklist (real hardware)",
    "   Follow: real_device_runtime_proof_checklist.md",
    `   Update: ${DEVICE_SIGNOFF_PATH}`,
    "   - testerName, date, deviceMatrix; all booleans true only after real runs",
    "",
    "10. Full orchestration",
    "    export VOICEMEMORY_STAGING_PROOF=1",
    "    export VOICEMEMORY_DEVICE_PROOF_REQUIRED=1",
    "    npm run staging:run-proof",
    "    (runs database, stripe, email, staging, device, deploy-secrets, aplus)",
    "",
    "11. Final gate",
    "    npm run validate:aplus",
    "    Exit 0 only when all code + live proof + sign-offs pass on staging host.",
    "",
    "Docs: STAGING_EXECUTION_ORDER.md, HOST_SETUP_CHECKLIST.md, staging_command_cheatsheet.md",
    "",
  ];
  console.log(lines.join("\n"));
}
