// Mocks generated by Mockito 5.4.6 from annotations
// in archiveme_mobile/test/ui/privacy_security_analytics_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:archiveme_mobile/features/caregiver/caregiver_access_service.dart'
    as _i2;
import 'package:archiveme_mobile/services/analytics_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCaregiverAccessOverview_0 extends _i1.SmartFake
    implements _i2.CaregiverAccessOverview {
  _FakeCaregiverAccessOverview_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i3.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logEvent(String? name, Map<String, Object>? parameters) =>
      super.noSuchMethod(
        Invocation.method(#logEvent, [name, parameters]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CaregiverAccessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaregiverAccessService extends _i1.Mock
    implements _i2.CaregiverAccessService {
  MockCaregiverAccessService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CaregiverAccessOverview> loadOverview() =>
      (super.noSuchMethod(
            Invocation.method(#loadOverview, []),
            returnValue: _i4.Future<_i2.CaregiverAccessOverview>.value(
              _FakeCaregiverAccessOverview_0(
                this,
                Invocation.method(#loadOverview, []),
              ),
            ),
          )
          as _i4.Future<_i2.CaregiverAccessOverview>);
}
